"""initial_healthcare_schema

Revision ID: 1f9db9cf741a
Revises: 
Create Date: 2026-08-17 08:45:26.727775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9db9cf741a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('head_doctor_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_event_id'), 'system_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_id'), 'system_events', ['id'], unique=False)
    op.create_index(op.f('ix_system_events_patient_id'), 'system_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_system_events_timestamp'), 'system_events', ['timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=100), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_resource', 'audit_logs', ['action', 'resource_type'], unique=False)
    op.create_index('idx_audit_actor_timestamp', 'audit_logs', ['actor_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('benchmark_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('applied_ddls', sa.JSON(), nullable=False),
    sa.Column('before_execution_time_ms', sa.Float(), nullable=False),
    sa.Column('after_execution_time_ms', sa.Float(), nullable=False),
    sa.Column('speedup_ratio', sa.Float(), nullable=False),
    sa.Column('before_cost', sa.Float(), nullable=False),
    sa.Column('after_cost', sa.Float(), nullable=False),
    sa.Column('cost_reduction_pct', sa.Float(), nullable=False),
    sa.Column('before_seq_scans', sa.Integer(), nullable=True),
    sa.Column('after_seq_scans', sa.Integer(), nullable=True),
    sa.Column('before_index_scans', sa.Integer(), nullable=True),
    sa.Column('after_index_scans', sa.Integer(), nullable=True),
    sa.Column('tested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_history_id'), 'benchmark_history', ['id'], unique=False)
    op.create_table('optimization_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_sql', sa.Text(), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_column', sa.String(length=100), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_recommendations_id'), 'optimization_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_query_fingerprint'), 'optimization_recommendations', ['query_fingerprint'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('ward_type', sa.String(length=50), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=True),
    sa.Column('occupied_beds', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_id', 'bed_number', name='uq_ward_bed_number')
    )
    op.create_index(op.f('ix_beds_id'), 'beds', ['id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('encounter_type', sa.String(length=50), nullable=False),
    sa.Column('encounter_date', sa.DateTime(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_doctor_id'), 'encounters', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_encounters_encounter_date'), 'encounters', ['encounter_date'], unique=False)
    op.create_index(op.f('ix_encounters_id'), 'encounters', ['id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.add_column('admissions', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.add_column('admissions', sa.Column('attending_doctor_name', sa.String(length=100), nullable=True))
    op.add_column('admissions', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index('idx_admissions_patient_status', 'admissions', ['patient_id', 'status'], unique=False)
    op.create_index('idx_admissions_ward_status', 'admissions', ['ward', 'status'], unique=False)
    op.create_index(op.f('ix_admissions_admission_date'), 'admissions', ['admission_date'], unique=False)
    op.create_index(op.f('ix_admissions_patient_id'), 'admissions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_admissions_status'), 'admissions', ['status'], unique=False)
    op.create_index(op.f('ix_admissions_ward'), 'admissions', ['ward'], unique=False)
    op.drop_constraint(op.f('admissions_patient_id_fkey'), 'admissions', type_='foreignkey')
    op.create_foreign_key(None, 'admissions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'admissions', 'wards', ['ward_id'], ['id'], ondelete='SET NULL')
    op.add_column('alerts', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('alerts', sa.Column('is_acknowledged', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_alerts_resolved_created', 'alerts', ['is_resolved', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_acknowledged'), 'alerts', ['is_acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_patient_id'), 'alerts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.drop_constraint(op.f('alerts_patient_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'users', ['acknowledged_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alerts', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'alerts', 'users', ['resolved_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('appointments', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('diagnoses', 'diagnosed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_diagnoses_icd10_code'), 'diagnoses', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_severity'), 'diagnoses', ['severity'], unique=False)
    op.drop_constraint(op.f('diagnoses_patient_id_fkey'), 'diagnoses', type_='foreignkey')
    op.drop_constraint(op.f('diagnoses_admission_id_fkey'), 'diagnoses', type_='foreignkey')
    op.create_foreign_key(None, 'diagnoses', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diagnoses', 'admissions', ['admission_id'], ['id'], ondelete='SET NULL')
    op.add_column('doctors', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('doctors', 'contact_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_unique_constraint(None, 'doctors', ['license_number'])
    op.drop_constraint(op.f('doctors_user_id_fkey'), 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('lab_results', sa.Column('ordered_by_doctor_name', sa.String(length=100), nullable=True))
    op.alter_column('lab_results', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_labs_patient_recorded', 'lab_results', ['patient_id', 'recorded_at'], unique=False)
    op.create_index('idx_labs_status_category', 'lab_results', ['status', 'category'], unique=False)
    op.create_index(op.f('ix_lab_results_admission_id'), 'lab_results', ['admission_id'], unique=False)
    op.create_index(op.f('ix_lab_results_category'), 'lab_results', ['category'], unique=False)
    op.create_index(op.f('ix_lab_results_patient_id'), 'lab_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_results_recorded_at'), 'lab_results', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_lab_results_status'), 'lab_results', ['status'], unique=False)
    op.create_index(op.f('ix_lab_results_test_name'), 'lab_results', ['test_name'], unique=False)
    op.drop_constraint(op.f('lab_results_patient_id_fkey'), 'lab_results', type_='foreignkey')
    op.drop_constraint(op.f('lab_results_admission_id_fkey'), 'lab_results', type_='foreignkey')
    op.create_foreign_key(None, 'lab_results', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_results', 'admissions', ['admission_id'], ['id'], ondelete='SET NULL')
    op.add_column('medications', sa.Column('unit_strength', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=True)
    op.add_column('model_predictions', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('model_predictions', sa.Column('confidence_score', sa.Float(), nullable=False, server_default='0.92'))
    op.add_column('model_predictions', sa.Column('clinical_recommendation', sa.Text(), nullable=True))
    op.alter_column('model_predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_predictions_patient_created', 'model_predictions', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_model_predictions_created_at'), 'model_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_predictions_patient_id'), 'model_predictions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_model_predictions_risk_level'), 'model_predictions', ['risk_level'], unique=False)
    op.drop_constraint(op.f('model_predictions_patient_id_fkey'), 'model_predictions', type_='foreignkey')
    op.create_foreign_key(None, 'model_predictions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.add_column('patients', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('patients', 'patient_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('patients', 'contact_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_patients_age_status', 'patients', ['age', 'status'], unique=False)
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.alter_column('prescriptions', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prescriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    op.drop_constraint(op.f('prescriptions_doctor_id_fkey'), 'prescriptions', type_='foreignkey')
    op.drop_constraint(op.f('prescriptions_patient_id_fkey'), 'prescriptions', type_='foreignkey')
    op.drop_constraint(op.f('prescriptions_admission_id_fkey'), 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'doctors', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'prescriptions', 'admissions', ['admission_id'], ['id'], ondelete='SET NULL')
    op.add_column('query_history', sa.Column('query_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('query_history', sa.Column('buffers_hit', sa.Integer(), nullable=True))
    op.add_column('query_history', sa.Column('buffers_read', sa.Integer(), nullable=True))
    op.add_column('query_history', sa.Column('plan_tree_json', sa.JSON(), nullable=True))
    op.add_column('query_history', sa.Column('has_bottleneck', sa.Boolean(), nullable=True))
    op.add_column('query_history', sa.Column('bottleneck_type', sa.String(length=100), nullable=True))
    op.alter_column('query_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_query_history_time_cost', 'query_history', ['execution_time_ms', 'cost_estimate'], unique=False)
    op.create_index(op.f('ix_query_history_execution_time_ms'), 'query_history', ['execution_time_ms'], unique=False)
    op.create_index(op.f('ix_query_history_has_bottleneck'), 'query_history', ['has_bottleneck'], unique=False)
    op.create_index(op.f('ix_query_history_query_fingerprint'), 'query_history', ['query_fingerprint'], unique=False)
    op.create_index(op.f('ix_query_history_timestamp'), 'query_history', ['timestamp'], unique=False)
    op.drop_constraint(op.f('query_history_user_id_fkey'), 'query_history', type_='foreignkey')
    op.create_foreign_key(None, 'query_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.add_column('vitals', sa.Column('blood_glucose_mgdl', sa.Float(), nullable=True))
    op.alter_column('vitals', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('idx_vitals_heart_rate'), table_name='vitals')
    op.create_index('idx_vitals_abnormal_recorded', 'vitals', ['is_abnormal', 'recorded_at'], unique=False)
    op.create_index('idx_vitals_patient_recorded', 'vitals', ['patient_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_vitals_admission_id'), 'vitals', ['admission_id'], unique=False)
    op.create_index(op.f('ix_vitals_is_abnormal'), 'vitals', ['is_abnormal'], unique=False)
    op.create_index(op.f('ix_vitals_patient_id'), 'vitals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vitals_recorded_at'), 'vitals', ['recorded_at'], unique=False)
    op.drop_constraint(op.f('vitals_patient_id_fkey'), 'vitals', type_='foreignkey')
    op.drop_constraint(op.f('vitals_admission_id_fkey'), 'vitals', type_='foreignkey')
    op.create_foreign_key(None, 'vitals', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vitals', 'admissions', ['admission_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitals', type_='foreignkey')
    op.drop_constraint(None, 'vitals', type_='foreignkey')
    op.create_foreign_key(op.f('vitals_admission_id_fkey'), 'vitals', 'admissions', ['admission_id'], ['id'])
    op.create_foreign_key(op.f('vitals_patient_id_fkey'), 'vitals', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_vitals_recorded_at'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_patient_id'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_is_abnormal'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_admission_id'), table_name='vitals')
    op.drop_index('idx_vitals_patient_recorded', table_name='vitals')
    op.drop_index('idx_vitals_abnormal_recorded', table_name='vitals')
    op.create_index(op.f('idx_vitals_heart_rate'), 'vitals', ['heart_rate'], unique=False)
    op.alter_column('vitals', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('vitals', 'blood_glucose_mgdl')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'query_history', type_='foreignkey')
    op.create_foreign_key(op.f('query_history_user_id_fkey'), 'query_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_query_history_timestamp'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_query_fingerprint'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_has_bottleneck'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_execution_time_ms'), table_name='query_history')
    op.drop_index('idx_query_history_time_cost', table_name='query_history')
    op.alter_column('query_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('query_history', 'bottleneck_type')
    op.drop_column('query_history', 'has_bottleneck')
    op.drop_column('query_history', 'plan_tree_json')
    op.drop_column('query_history', 'buffers_read')
    op.drop_column('query_history', 'buffers_hit')
    op.drop_column('query_history', 'query_fingerprint')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key(op.f('prescriptions_admission_id_fkey'), 'prescriptions', 'admissions', ['admission_id'], ['id'])
    op.create_foreign_key(op.f('prescriptions_patient_id_fkey'), 'prescriptions', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('prescriptions_doctor_id_fkey'), 'prescriptions', 'doctors', ['doctor_id'], ['id'])
    op.drop_index(op.f('ix_prescriptions_status'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.alter_column('prescriptions', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('prescriptions', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_index('idx_patients_age_status', table_name='patients')
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('patients', 'contact_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('patients', 'patient_code',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'status')
    op.drop_constraint(None, 'model_predictions', type_='foreignkey')
    op.create_foreign_key(op.f('model_predictions_patient_id_fkey'), 'model_predictions', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_model_predictions_risk_level'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_patient_id'), table_name='model_predictions')
    op.drop_index(op.f('ix_model_predictions_created_at'), table_name='model_predictions')
    op.drop_index('idx_predictions_patient_created', table_name='model_predictions')
    op.alter_column('model_predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('model_predictions', 'clinical_recommendation')
    op.drop_column('model_predictions', 'confidence_score')
    op.drop_column('model_predictions', 'model_name')
    op.drop_index(op.f('ix_medications_name'), table_name='medications')
    op.drop_column('medications', 'unit_strength')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.create_foreign_key(op.f('lab_results_admission_id_fkey'), 'lab_results', 'admissions', ['admission_id'], ['id'])
    op.create_foreign_key(op.f('lab_results_patient_id_fkey'), 'lab_results', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_lab_results_test_name'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_status'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_recorded_at'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_category'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_admission_id'), table_name='lab_results')
    op.drop_index('idx_labs_status_category', table_name='lab_results')
    op.drop_index('idx_labs_patient_recorded', table_name='lab_results')
    op.alter_column('lab_results', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('lab_results', 'ordered_by_doctor_name')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key(op.f('doctors_user_id_fkey'), 'doctors', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'doctors', type_='unique')
    op.alter_column('doctors', 'contact_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('doctors', 'created_at')
    op.drop_column('doctors', 'is_available')
    op.drop_column('doctors', 'department_id')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.create_foreign_key(op.f('diagnoses_admission_id_fkey'), 'diagnoses', 'admissions', ['admission_id'], ['id'])
    op.create_foreign_key(op.f('diagnoses_patient_id_fkey'), 'diagnoses', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_diagnoses_severity'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_icd10_code'), table_name='diagnoses')
    op.alter_column('diagnoses', 'diagnosed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'doctors', ['doctor_id'], ['id'])
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_column('appointments', 'notes')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_patient_id_fkey'), 'alerts', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patient_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_acknowledged'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index('idx_alerts_resolved_created', table_name='alerts')
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'resolved_by_user_id')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'acknowledged_by_user_id')
    op.drop_column('alerts', 'is_acknowledged')
    op.drop_column('alerts', 'category')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.create_foreign_key(op.f('admissions_patient_id_fkey'), 'admissions', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_admissions_ward'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_status'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_patient_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_admission_date'), table_name='admissions')
    op.drop_index('idx_admissions_ward_status', table_name='admissions')
    op.drop_index('idx_admissions_patient_status', table_name='admissions')
    op.drop_column('admissions', 'notes')
    op.drop_column('admissions', 'attending_doctor_name')
    op.drop_column('admissions', 'ward_id')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_encounter_date'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_doctor_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_beds_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_wards_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_optimization_recommendations_query_fingerprint'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_id'), table_name='optimization_recommendations')
    op.drop_table('optimization_recommendations')
    op.drop_index(op.f('ix_benchmark_history_id'), table_name='benchmark_history')
    op.drop_table('benchmark_history')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_actor_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_action_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_system_events_timestamp'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_patient_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_id'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
